version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "monthly"
  labels:
    - 'dependencies'
  rebase-strategy: disabled

- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: "monthly"
    time: "04:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  versioning-strategy: increase
  rebase-strategy: disabled
  allow:
      - dependency-name: "meilisearch"
      - dependency-name: "to-factory"
      - dependency-name: "zepto"
      - dependency-name: "autocomplete.js"
