version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "monthly"
  labels:
    - 'skip-changelog'
    - 'dependencies'
  rebase-strategy: disabled

- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: "monthly"
    time: "04:00"
  open-pull-requests-limit: 10
  labels:
  - skip-changelog
  - dependencies
  versioning-strategy: increase
  rebase-strategy: disabled
  ignore:
      - dependency-name: "*eslint*"
      - dependency-name: "babel-eslint"
      - dependency-name: "*prettier*"
      - dependency-name: "*jest*"
      - dependency-name: "pretty-bytes-cli"
      - dependency-name: "concurrently"
      - dependency-name: "cypress"
- package-ecosystem: npm
  directory: "/playground/javascript"
  schedule:
    interval: "monthly"
    time: "04:00"
  open-pull-requests-limit: 10
  labels:
  - skip-changelog
  - dependencies
  versioning-strategy: increase
  rebase-strategy: disabled
  ignore:
      - dependency-name: "parcel-bundler"
- package-ecosystem: npm
  directory: "/playground/html"
  schedule:
    interval: "monthly"
    time: "04:00"
  open-pull-requests-limit: 10
  labels:
  - skip-changelog
  - dependencies
  versioning-strategy: increase
  rebase-strategy: disabled
  ignore:
      - dependency-name: "parcel-bundler"
